apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-config2
  namespace: argocd # Use the same namespace as your application.
data:
  database.host: "bitnami-postgresql"
  database.port: "5432"
  app.logging.level: "info"
  app.feature.enabled: "true"