apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  # syncPolicy:
  #   automated:
  #     selfHeal: true
  source:
    repoURL: https://github.com/dekemre/testemre.git
    path: nginx
    targetRevision: main
    # helm:
    #   values: | # Inline values go here